model:
    name: "decoder_only"
    num_events: 3
    event_embedding_size: 32
    time_embedding_size: 32
    hidden_size: 64
    latent_size: 0
    intensity_layer_size: 16
    intensity_num_layers: 2
    intensity_act_func: "relu"
    layer_norm: "identity"
optimizer:
    name: "adam"
#    lr: 0.0003
#    weight_decay: 0.000001
training:
    epochs: 5
    batch_size: 32
    train_mc_samples: 100
    valid_mc_samples: 500
train_data: "/home/alexjb/Research/vae_mpp/data/1_pp/training.pickle"
validation_data: "/home/alexjb/Research/vae_mpp/data/1_pp/validation.pickle"
evaluation_data: "/home/alexjb/Research/vae_mpp/data/1_pp/eval.pickle"
point_process_objects: "/home/alexjb/Research/vae_mpp/data/1_pp/single_pp_obj.pickle"